version: '3.8'

services:
  web-monitor:
    build: .
    container_name: smic-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/var/log